// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  STARTUP

  LOGIN
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  REQUEST_QUESTIONS
  RECEIVE_QUESTIONS
  RECEIVE_QUESTIONS_FAILURE

  REQUEST_SETTINGS
  RECEIVE_SETTINGS
  RECEIVE_SETTINGS_FAILURE

  EDIT_SETTINGS
  EDIT_SETTINGS_SUCCESS
  EDIT_SETTINGS_FAILURE

  REQUEST_CATEGORIES
  RECEIVE_CATEGORIES
  RECEIVE_CATEGORIES_FAILURE

  CHANGE_VIEWING

  ADD_QUESTION
  ADD_QUESTION_SUCCESS
  ADD_QUESTION_FAILURE

  EDIT_QUESTION
  EDIT_QUESTION_SUCCESS
  EDIT_QUESTION_FAILURE

  DELETE_QUESTION
  DELETE_QUESTION_SUCCESS
  DELETE_QUESTION_FAILURE

  ADD_LEVEL
  ADD_LEVEL_SUCCESS
  ADD_LEVEL_FAILURE

  EDIT_LEVEL
  EDIT_LEVEL_SUCCESS
  EDIT_LEVEL_FAILURE

  DELETE_LEVEL
  DELETE_LEVEL_SUCCESS
  DELETE_LEVEL_FAILURE
`)
