
export const REQUEST_QUESTIONS = 'InterviewApp/Questions/REQUEST_QUESTIONS'
export const RECEIVE_QUESTIONS_SUCCESS = 'InterviewApp/Questions/RECEIVE_QUESTIONS_SUCCESS'
export const RECEIVE_QUESTIONS_FAILURE = 'InterviewApp/Questions/RECEIVE_QUESTIONS_FAILURE'
export const CHANGE_VIEWING = 'InterviewApp/Questions/CHANGE_VIEWING'
export const ADD_QUESTION = 'InterviewApp/Questions/ADD_QUESTION'
export const ADD_QUESTION_SUCCESS = 'InterviewApp/Questions/ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_FAILURE = 'InterviewApp/Questions/ADD_QUESTION_FAILURE'
export const ADD_CATEGORY = 'InterviewApp/Questions/ADD_CATEGORY'
export const ADD_CATEGORY_SUCCESS = 'InterviewApp/Questions/ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAILURE = 'InterviewApp/Questions/ADD_CATEGORY_FAILURE'
